# Generated by Django 5.0 on 2024-02-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
